# Generated by Django 5.1.5 on 2025-02-26 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contacts', models.CharField(max_length=15)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_first_name', models.CharField(max_length=100)),
                ('card_last_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_rooms.hotelroom')),
            ],
        ),
    ]
