# Generated by Django 5.1.5 on 2025-02-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='card_first_name',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='card_last_name',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='total_payment',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(max_length=16)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking_rooms.roombooking')),
            ],
        ),
    ]
