# Generated by Django 5.1.5 on 2025-02-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms', '0002_remove_roombooking_card_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('cancelled', 'Cancelled'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cardholder_first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cardholder_last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='booking_rooms.roombooking'),
        ),
    ]
