# Generated by Django 5.1.5 on 2025-02-27 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms', '0003_roombooking_status_transaction_cardholder_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_rooms.roombooking'),
        ),
    ]
