# Generated by Django 5.1.5 on 2025-02-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms', '0004_alter_transaction_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_rooms.roombooking'),
        ),
    ]
