# Generated by Django 5.1.5 on 2025-02-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms', '0005_alter_transaction_booking'),
        ('hotel_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_rooms.hotelroom'),
        ),
    ]
