# Generated by Django 5.1.5 on 2025-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomsTitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('descripFull', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('checkIn', models.CharField(max_length=50)),
                ('checkOut', models.CharField(max_length=50)),
                ('specialCheckIn', models.TextField()),
                ('petsAllowed', models.BooleanField(default=False)),
                ('maxOccupancy', models.IntegerField()),
                ('amenities', models.JSONField()),
                ('imgSrc', models.URLField()),
                ('extraImages', models.JSONField()),
            ],
        ),
    ]
